"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestStarfallNight,
	#superclass : #PackageManifest,
	#category : #StarfallNight
}

{ #category : #code-critics }
ManifestStarfallNight class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#BaselineOfStarfallNight)) #'2017-12-02T09:16:59.802645+09:00') )
]
